version: '3.8'

services:
  next-app:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env.local  # Path to .env file for Next.js app
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "3000:3000"
