version: '3.8'
include:
  - search-service.yaml
services:
  image_upload:
    build:
      context: ./image_upload
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    restart: always
    env_file:
      - ./image_upload/.env
    volumes:
      - ./image_upload:/app  # Mount the local streamlit directory to the /app directory in the container
  streamlit:
    build:
      context: ./streamlit
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    restart: always
    env_file:
      - ./streamlit/.env
    volumes:
      - ./streamlit:/app  # Mount the local streamlit directory to the /app directory in the container