services:
  search:
    build:
      context: ./search
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    environment:
      - FLASK_ENV=production
    env_file:
      - ./search/.env  # Path to .env file for search service
    volumes:
      - ./search:/app  # Mount the local streamlit directory to the /app directory in the container