import type { Metadata } from 'next';
import './globals.css';
import { ChakraProvider } from '@chakra-ui/react';
import { Almarai } from 'next/font/google';
import { HeaderProvider } from './components/Header';

const almarai = Almarai({
  subsets: ['arabic'],
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: 'My Next.js App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={almarai.className}>
        <ChakraProvider>
          <HeaderProvider>
            {children}
          </HeaderProvider>
        </ChakraProvider>
      </body>
    </html>
  );
}
 
